### ISSUE TITLE
[BUG] incorrect display of info in battery section of settings

### ISSUE THREAD

**Issue by ramandy007** [Xtended-Devices/device_xiaomi_whyred#1]
- I assume that active battery drain  value is shown in "current battery capacity" field instead of {current battery capacity}.

- String "Def"  is  initially shown instead of actual values set in Smart charging section.

build date:= 12/06/2020 version:=XQ-v10.0-OFFICIAL

![photo6280498662710815068](https://user-images.githubusercontent.com/29678549/84571131-0439cb80-adaf-11ea-9d77-928491e6b016.jpg)

![photo6280498662710815069](https://user-images.githubusercontent.com/29678549/84571134-09971600-adaf-11ea-9612-ff0508e1e21b.jpg)

![photo6280498662710815070](https://user-images.githubusercontent.com/29678549/84571146-14ea4180-adaf-11ea-94e4-a060a553051d.jpg)

**Comment by SreekanthPalakurthi** [comment]
LET IT SETTLE BRUUUHHHH
It'll be fine after one charge cycle
